version: '3.8'

services:
  http11:
    build:
      context: ./server/
      args: 
        HTTP_VERSION: ''
    hostname: http11
    container_name: http11
    ports:
      - '60001:80'

  http20:
    build:
      context: ./server/
      args: 
        HTTP_VERSION: 'http2'
    hostname: http20
    container_name: http20
    ports:
      - '60002:80'

  netdata:
    build: ./netdata/
    ports:
      - 19999:19999
    hostname: netdata
    container_name: netdata
