version: '3'

networks:
  network_default:
    driver: bridge

services:
  http-1.1:
    build:
      context: ./server/
      args: 
        HTTP_VERSION: ''
    networks:
      - network_default
    ports:
      - '60001:80'

  http-2:
    build:
      context: ./server/
      args: 
        HTTP_VERSION: 'http2'
    networks:
      - network_default
    ports:
      - '60002:80'
